apiVersion: v1
kind: ConfigMap
metadata:
  name: github-app-private-key
  namespace: dev
data:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA7mBztB0ZXQfTQC5k+n9+Uang/PeqzkpDJDpncdjI/TuzEvvK
    nkJi29yOBrz0H0qWwzwt9kuv+BL9peZDcAvJgLLONg4DJI5foQMcK4ePLb2p5Zcj
    Nd5HYQFpH3ugRgSEd1bTw9rwArc5WxVxHGok7ZA8GAQqoT2Y5oXOPBt1pbYnwaRs
    /xo0TuZQn0zbv20Kwt6RyAy61jOky7xp+BrZ93mPUxZgOpDzjrHfyv6jdVxE40sH
    hdwJRwPFpOL8BfpCgFVY9UQVDVgh5Xu0yK6HQ5nqvCPhrtNJ2LCZNwBEnu9GAwK+
    6QDi359jvR16S32SjOG/FQwUbNyXe3RBbNieqwIDAQABAoIBAQCOWUq+5CGhTGr6
    iLoEXN4yJiAU8FEvn2k42Ses9KgRkPT/AR2eJEakxLCLlYqypPgi3m0UB16t5alS
    yI68+kz6bcx2uydlTSAOJq1L0UfPKNOsJvT/1h0J8K21/z1WkpwIJ/GNo9BvzrqR
    idxh+4DR3LAGJ3bNktsbzgu6GSvIKDfLFv52TMVLhqG6Ipoc5XoYMnGixRIReZRI
    2sPthaDV7FlugcszaL0PbVqhcd1zFyD4lGf6pKQlgtcZezr+ob5J80aqSWpcfRgx
    NrIiSXAhOXVC0yNP47Eoy4JWwULOuUJ7B9o5IrrVKO84DKSix7SmRrSUdsQacRPV
    JcDmFMYBAoGBAPgNHvNaBJcbzWMwccHN+iCAvqXdD/TnPqQ9/wnY1gzUfFzKsJKy
    hs7qkjvzBs92tfj94wIU9YLsjt/tzrxpYPky+juJU2ypriMlf/ZVqUfDEpgJewnH
    GMXYRaB0I947VlvZIV24g/zocDmpa6i0GtQUTRVjnF/k5EoxV9bMlRbzAoGBAPYD
    934puH6wZyCAnq8xS2mKd8Wuw339HV0OyuXTA2Yt/zCuvBWby3LE6z5vb1uaQAQ0
    mWrdCX1JPx+4oj5lW/mu/nx4L1GxEG1jKBkhn5tTCwxj5lf9c8IWoLHJU4vAxWM6
    WWQdCnptbRhHNvgBblARNNPMXVVi/aahBXTOLDdpAoGBANInK6W5ClKLt4LltDsi
    K1wGN3+GvtIaaLP14nGRSCgujf5/qwFeR2Be0+3+hDKYvKtrTjyhTS/TA2ksrQ5r
    qUD3s5FlU0yopWQZjURCZtzppIMy5Q7vo0lbZgH+47SQSSYf22jvvsMymoH/y7pu
    fJxZZsVMU1vbLJ6/F1Bgm5+JAoGBANyG48ThKzPNdzQod5Z9rqb167V1mmIGkdrI
    FtL7W3Gty7Jc/9ay6CWCJYm7JGxNkhLy/49OgmIfVYle3XjnLRJdblwu8+Pbv+j+
    WIRmoob+YsoBhwra9HhIBlY4LT76VzZCqLzYV3s1OfToaXrY9YSqV9t/ty6CZPOI
    Jbb11ab5AoGBAMFdDqzIHvLf6RyZo2qZzZrOhFcCbdJWaOmstG31sR2gTzk7ML+C
    pAA0RFQHa5N9r7det/QbgSvXW9EWxKieA53Jux1gdxm1RkOkHI+w/RaT6XhV4zXo
    pju+92zeAtm9nWFMKnBMbULwhz+5IDLnBo3N0OW31Wz1LVTfGd0De5Go
    -----END RSA PRIVATE KEY-----

