apiVersion: v1
kind: ConfigMap
metadata:
  name: github-app-private-key
  namespace: dev
data:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAxT18+Y0Hs94sSm6XWHHLPsVW81OAPok1XT/zidPHjtnmbaX1
    Awa3tOlhKRQ90Qowl4mXpcQJUSClarXX+TOH8gNynK2cQE/BQGr38pgXVS2RaJne
    t1xkbNYEIbJjJmCr8l64mCYXYSoWeudzcvgqPaL6erLeRGO7CfvmJIVOGo7nMgZW
    QwSYwKBL26hJSLS5eIK14Ctv0TYMwG7SG3xuhGP5c8urBFLj5g74wNbnds3mMVip
    putrcgGPYcMvppy3McjWr+9gO+m/AD7oz/8A+ZKYszAv4XUsro9J+PA3fGxNXk7u
    6EU2QWRs4TdfluLIq8vZyOTFShObS/UAM62eXQIDAQABAoIBAQC4OUItY8g5+92q
    d7jsZvzK2E7qXqd9wXISctTpeuD9UBClgUhjVzbmxsR1Ne62/Kl+IIl/zqZVHATk
    sovSuorTRN0b8hvrBZMes8p60AubB0C1TmJzKNyzuwGI57Er+0cezdHkak+T9Veh
    2+Q9EgWCJGOHjuGDRxM/tAO1QL0+l28KKiDpiJK1+tJ4s4sIXJj1ZHOyLpbswJ2+
    t9pVfdvBOVPchIi0qWsWGuA4WqNw1WAPhIQCDYZYRROo6/RUZAklljRzHpvS2ITb
    mqVHbVOmMY6p+C+b9bESa6MC5RT1DhllkmQXb6oiXJNO38sqbqOp4nzYeJAQNGuk
    1o8yRuuBAoGBAOUWYMWtOgAXz7fiWF7tACjXYgD15Hpa1tSWeMr/DNqaSVX9fG1k
    spu27DXunpxAVxmfdUI2tnKdgd4ekNR3jq7Abt4aTuJ6vCA/XudRq/gQJdgxx9Oo
    Lhf5LKLTWVIbE/ZetaQTu1uRANPjnJELuIsOE3LjOx2KaDFGchZq9K/VAoGBANxp
    VISTRp9KQenT6j0/4xC61X1dXIR+9KnfOiBIP2TPZoP81yga+ZkJQPJZy1+w4bEq
    GcqLnnHwTey5jd+5ZmeOPqT8Qv+p+VgS7n0+ef/7DUcF+JbBy6biQ//3RGP1LlLe
    KK8lFqMGJWBdu1o4JkAfiwn04UavcNBhJGmSS4BpAoGAAOmO5xqigX+Wxy+ylGYz
    OvZooIJaL5aPBne28XAEmBZHNn108maVQ4N9+1UA8rRa5HI7IFFhdqFj9AOBJid3
    vQBtMJtANyyv9RzrftZXbfx6ehrwpcokrNnEML3QvD/5W2DTLl0ZwOqZ6z4b0IQQ
    bxVWRH3dLWfwtEmIiMhSQyUCgYEAnEk7mr3rR6uZzTlsUH3qfcRc+QWoQnLa/VDB
    oH5aJRtC77fqwA9QiIkdOjsdj/6WKc9Wdl5FvTjNqFtyE/8cc7VTCh2tTCe0HBVg
    cgJI84+KPKApQoyr4OtzmB42qkIB1NSeOIKt6G7FNe2AmVpTFQjIyAiRbFOeRMN8
    1DbdvnECgYAwHZTlrhFMUNZ2FY0oA3naNrwJ3TQcWo6KsNh3RFtfWMm0z+X9UrUK
    ZLHjSd4EH6ERjcphQxPvqASnjISSHDuHAXvr/t6vkfUIlfIzI1oNnWqblR3IyVuY
    LkGoCl8L66K919jlJaAr2vZM5alJmYWdejXmvPtrhxIVeBaHp0p7yA==
    -----END RSA PRIVATE KEY-----

